apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blackjack-ingress
  namespace: default
  labels:
    team: mjd-software
spec:
  rules:
  - host: myblackjack.localhost
    http:
      paths:
        - backend:
            serviceName: blackjack
            servicePort: 8080